apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: demo-app-dev
  labels:
    app: api-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        environment: dev
    spec:
      containers:
      - name: api-service
        image: httpd:2.4
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: SERVICE_NAME
          value: "api-service"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
