apiVersion: batch/v1
kind: Job
metadata:
  name: dev-api-post-sync-validation
  namespace: demo-app-dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: post-sync-validation
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "=== DEV API Service Post-Sync Validation ==="
          echo "Service: api-service"
          echo "Environment: development"
          echo "Validation Level: Basic"
          echo ""
          
          # Wait for deployment to be ready
          echo "Waiting for deployment to stabilize..."
          sleep 10
          
          # Basic health check
          echo "Performing basic health check..."
          
          # Check if service is available (using kubernetes DNS)
          if nslookup api-service.demo-app-dev.svc.cluster.local; then
            echo "✅ DNS resolution successful for api-service"
          else
            echo "❌ DNS resolution failed for api-service"
            exit 1
          fi
          
          echo ""
          echo "=== Dev API Service Validation Complete ==="
          echo "Status: SUCCESS"
          echo "Duration: ~15 seconds (basic validation)"
      restartPolicy: Never
  backoffLimit: 2
