apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: demo-app-dev
  labels:
    app: api-service
    environment: dev
spec:
  selector:
    app: api-service
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
