apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-api-service
  namespace: argocd
  labels:
    environment: production
    service: api-service
    app.kubernetes.io/part-of: selective-sync-demo
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
    targetRevision: feature/app-of-apps-selective-sync
    path: environments/api-service/production
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
