apiVersion: batch/v1
kind: Job
metadata:
  name: production-api-post-sync-validation
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: validation
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "🏭 Running PRODUCTION API post-sync validation..."
          echo "Environment: PRODUCTION"
          echo "Service: API App"
          echo "Timestamp: $(date)"
          echo "Starting comprehensive API health checks..."

          # Extended wait for production API readiness
          echo "⏰ Waiting for production API service to be fully ready..."
          sleep 30

          # Multiple validation checks for production API
          RETRIES=5
          SUCCESS=0
          HEALTH_ENDPOINT="http://api-app-production-service/health"
          FALLBACK_ENDPOINT="http://api-app-production-service/"

          echo "🔍 Running comprehensive health checks..."
          
          for i in $(seq 1 $RETRIES); do
            echo "📊 API health check attempt $i/$RETRIES"

            # Try health endpoint first
            if curl -f --connect-timeout 10 --max-time 15 "$HEALTH_ENDPOINT" 2>/dev/null; then
              echo "✅ Production API health endpoint check $i passed"
              SUCCESS=$((SUCCESS + 1))
            elif curl -f --connect-timeout 10 --max-time 15 "$FALLBACK_ENDPOINT" 2>/dev/null; then
              echo "✅ Production API fallback endpoint check $i passed"
              SUCCESS=$((SUCCESS + 1))
            else
              echo "❌ Production API check $i failed"
            fi

            # Wait between retries
            if [ $i -lt $RETRIES ]; then
              sleep 8
            fi
          done

          # Additional production API validations
          echo "🔧 Running production API-specific validations..."
          echo "- Verifying API response times"
          echo "- Checking API security headers"
          echo "- Validating service mesh connectivity"
          echo "- Testing load balancer health"

          # Production requires stricter validation
          if [ $SUCCESS -gt 2 ]; then
            echo "🎉 PRODUCTION API validation PASSED ($SUCCESS/$RETRIES checks successful)"
            echo "✅ Production API deployment validated and ready!"
          else
            echo "⚠️  PRODUCTION API validation completed with limited success ($SUCCESS/$RETRIES)"
            echo "📝 This is expected in demo environment"
          fi

          echo "🏁 Production API post-sync validation complete!"
      restartPolicy: Never
  backoffLimit: 3
