apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps
    app.kubernetes.io/part-of: selective-sync-demo
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
    targetRevision: HEAD
    path: apps/environments
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
