# GitHub Repository Secret Template for ArgoCD
# 
# INSTRUCTIONS FOR DEPLOYMENT:
# 1. Copy this file: cp github-repo-secret.template.yaml github-repo-secret.yaml
# 2. Replace the placeholder values with your actual credentials:
#    - YOUR_GITHUB_USERNAME: Your GitHub username
#    - YOUR_PERSONAL_ACCESS_TOKEN: GitHub token with 'repo' scope
# 3. Apply the secret: kubectl apply -f github-repo-secret.yaml
# 4. NEVER commit the actual github-repo-secret.yaml file (it's in .gitignore)
#
# TO CREATE A GITHUB PERSONAL ACCESS TOKEN:
# 1. Go to GitHub → Settings → Developer settings → Personal access tokens
# 2. Create token with 'repo' scope
# 3. Copy the token value (you won't see it again!)

apiVersion: v1
kind: Secret
metadata:
  name: argocd-selective-sync-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  url: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
  username: YOUR_GITHUB_USERNAME
  password: YOUR_PERSONAL_ACCESS_TOKEN
