apiVersion: v1
kind: Secret
metadata:
  name: argocd-selective-sync-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  url: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
  username: YOUR_GITHUB_USERNAME
  password: YOUR_PERSONAL_ACCESS_TOKEN
