apiVersion: batch/v1
kind: Job
metadata:
  name: dev-api-post-sync-validation
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: validation
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "🔧 Running DEV API post-sync validation..."
          echo "Environment: DEV"
          echo "Service: API App"
          echo "Timestamp: $(date)"
          echo "Checking API service health..."

          # Wait for API service to be ready
          echo "⏰ Waiting for API service to initialize..."
          sleep 15

          # Basic API health check
          if curl -f --connect-timeout 5 --max-time 10 http://api-app-dev-service/health 2>/dev/null; then
            echo "✅ DEV API service is responding"
          elif curl -f --connect-timeout 5 --max-time 10 http://api-app-dev-service/ 2>/dev/null; then
            echo "✅ DEV API service is responding (fallback endpoint)"
          else
            echo "⚠️  DEV API service not yet ready, but that's ok for demo"
          fi

          # Additional API-specific validations
          echo "🔍 Running API-specific validations..."
          echo "- Checking service discovery"
          echo "- Validating API endpoints"
          echo "- Testing connectivity"

          echo "🎉 DEV API post-sync validation complete!"
      restartPolicy: Never
  backoffLimit: 2
