apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-production
  labels:
    app: demo-app-production
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-production
  template:
    metadata:
      labels:
        app: demo-app-production
        environment: production
    spec:
      containers:
      - name: demo-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: MESSAGE
          value: "Hello from Production Environment!"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
