apiVersion: v1
kind: Service
metadata:
  name: api-app-dev-service
  labels:
    app: api-app-dev
    environment: dev
    component: backend
spec:
  selector:
    app: api-app-dev
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
