apiVersion: batch/v1
kind: Job
metadata:
  name: dev-post-sync-validation
  namespace: demo-app-dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: validation
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "🚀 Running DEV post-sync validation..."
          echo "Environment: DEV"
          echo "Timestamp: $(date)"
          echo "Checking service health..."

          # Wait for service to be ready
          sleep 10

          # Basic health check
          if curl -f --connect-timeout 5 --max-time 10 http://demo-app-service/; then
            echo "✅ DEV service is responding"
          else
            echo "⚠️  DEV service not yet ready, but that's ok for demo"
          fi

          echo "🎉 DEV post-sync validation complete!"
      restartPolicy: Never
  backoffLimit: 2
