apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-dev
  labels:
    app: demo-app-dev
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-dev
  template:
    metadata:
      labels:
        app: demo-app-dev
        environment: dev
    spec:
      containers:
      - name: demo-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: MESSAGE
          value: "Hello from Development Environment!"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
