apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-demo-app
  namespace: argocd
  labels:
    environment: dev
    service: demo-app
    app.kubernetes.io/part-of: selective-sync-demo
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
    targetRevision: HEAD
    path: environments/demo-app/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
