apiVersion: batch/v1
kind: Job
metadata:
  name: production-api-post-sync-validation
  namespace: demo-app-prod
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: post-sync-validation
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "=== PRODUCTION API Service Post-Sync Validation ==="
          echo "Service: api-service"
          echo "Environment: production"
          echo "Validation Level: Enhanced"
          echo ""
          
          # Wait for deployment to be ready (longer for production)
          echo "Waiting for production deployment to stabilize..."
          sleep 20
          
          # Enhanced health check for production
          echo "Performing enhanced health checks..."
          
          # Check if service is available (using kubernetes DNS)
          if nslookup api-service.demo-app-prod.svc.cluster.local; then
            echo "✅ DNS resolution successful for api-service"
          else
            echo "❌ DNS resolution failed for api-service"
            exit 1
          fi
          
          # Additional production checks
          echo "Running production-specific validations..."
          
          # Simulate load balancer check
          echo "Checking LoadBalancer service configuration..."
          sleep 5
          echo "✅ LoadBalancer service validated"
          
          # Simulate replica health check
          echo "Verifying all 3 replicas are healthy..."
          sleep 3
          echo "✅ All replicas validated"
          
          echo ""
          echo "=== Production API Service Validation Complete ==="
          echo "Status: SUCCESS"
          echo "Duration: ~30 seconds (enhanced validation)"
      restartPolicy: Never
  backoffLimit: 3
