apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: demo-app-prod
  labels:
    app: api-service
    environment: production
spec:
  selector:
    app: api-service
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
