apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-demo-app
  namespace: argocd
  labels:
    environment: dev
    service: demo-app
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-selective-sync-demo.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  # Post-sync hook specific to dev environment
  operation:
    sync:
      hooks:
      - name: dev-post-sync-validation
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: dev-post-sync-validation
            namespace: demo-app-dev
          spec:
            template:
              spec:
                containers:
                - name: validation
                  image: curlimages/curl:latest
                  command:
                  - /bin/sh
                  - -c
                  - |
                    echo "🚀 Running DEV post-sync validation..."
                    echo "Environment: DEV"
                    echo "Timestamp: $(date)"
                    echo "Checking service health..."

                    # Wait for service to be ready
                    sleep 10

                    # Basic health check
                    if curl -f --connect-timeout 5 --max-time 10 http://demo-app-service/; then
                      echo "✅ DEV service is responding"
                    else
                      echo "⚠️  DEV service not yet ready, but that's ok for demo"
                    fi

                    echo "🎉 DEV post-sync validation complete!"
                restartPolicy: Never
            backoffLimit: 2
