apiVersion: v1
kind: Service
metadata:
  name: api-app-production-service
  labels:
    app: api-app-production
    environment: production
    component: backend
spec:
  selector:
    app: api-app-production
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
