apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    app: demo-app
    environment: dev
spec:
  selector:
    app: demo-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
